Repository CS2113-AY1819S1-T16-1/main, pull requests merged in 2018-10, with the labels that each got.

#49 Updated documents on features coming in version and developer role
  docs/AboutUs.adoc
  docs/UserGuide.adoc
Labels: Changes in Documentation

#53 added 'add course' command, renamed old AB4 commands for student mana…
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CourseAddCommandParser.java
  src/main/java/seedu/address/model/Course.java
  src/main/java/seedu/address/model/CourseManager.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/StudentDatabase.java
  src/main/java/seedu/address/model/student/Student2.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#51 Class Create feature
  src/main/java/seedu/address/logic/commands/ClassCreateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClassCreateCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/classroom/ClassModule.java
  src/main/java/seedu/address/model/classroom/ClassName.java
  src/main/java/seedu/address/model/classroom/Classroom.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/main/java/seedu/address/model/classroom/Enrollment.java
  src/test/java/seedu/address/logic/commands/ClassCreateCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClassCreateCommandParserTest.java
  src/test/java/seedu/address/model/classroom/ClassModuleTest.java
  src/test/java/seedu/address/model/classroom/ClassNameTest.java
  src/test/java/seedu/address/model/classroom/ClassroomTest.java
  src/test/java/seedu/address/model/classroom/EnrollmentTest.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#57 Added support to add notes (WIP)
  classes.xml
  courseList.xml
  notes.xml
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/TrajectoryParser.java
  src/main/java/seedu/address/model/NotesManager.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/note/Note.java
Labels: Changes in Code, Changes in Shared Code

#59 Minor bug fix with xml elements
  src/main/java/seedu/address/model/classroom/ClassModule.java
  src/main/java/seedu/address/model/classroom/ClassName.java
  src/main/java/seedu/address/model/classroom/Enrollment.java
Labels: Changes in Code

#55 added command to list courses, updated dev and user guide
  docs/DeveloperGuide.adoc
  docs/LearningOutcomes.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/CourseListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/StorageController.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code, Pending Changes (DO NOT REVIEW)

#56 Add support for adding a module to Trajectory
  src/main/java/seedu/address/logic/commands/ModuleAddCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ModuleAddCommandParser.java
  src/main/java/seedu/address/model/Module.java
  src/main/java/seedu/address/model/ModuleManager.java
  src/main/java/seedu/address/model/StorageController.java
Labels: Changes in Code, Changes in Shared Code

#50 Changed UG and DG as well as added code implementation for Gradebook
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/gradebook/Component.java
  src/main/java/seedu/address/model/gradebook/MaxMarks.java
  src/main/java/seedu/address/model/gradebook/Name.java
  src/main/java/seedu/address/model/gradebook/UniqueComponentList.java
  src/main/java/seedu/address/model/gradebook/Weightage.java
  src/main/java/seedu/address/model/gradebook/exceptions/DuplicateComponentException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code, Pending Changes (DO NOT REVIEW)

#61 Fixed errors, disabled some tests.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TrajectoryParser.java
  src/main/java/seedu/address/model/Course.java
  src/main/java/seedu/address/model/NotesManager.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/classroom/ClassModule.java
  src/main/java/seedu/address/model/classroom/ClassName.java
  src/main/java/seedu/address/model/classroom/Enrollment.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code, Changes in Testing Code, Changes in UX/UI Design

#64 Added class listing feature with minor bug fix
  src/main/java/seedu/address/logic/commands/ClassListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/classroom/Classroom.java
  src/main/java/seedu/address/model/classroom/Enrollment.java
  src/test/java/seedu/address/logic/commands/ClassCreateCommandTest.java
Labels: Changes in Code

#63 Implemented "gradebook add" command
  classes.xml
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/LearningOutcomes.adoc
  docs/UserGuide.adoc
  docs/images/tristyxxnana.png
  gradebook.xml
  modules.xml
  src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
  src/main/java/seedu/address/logic/commands/GradebookListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GradebookAddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/gradebook/Component.java
  src/main/java/seedu/address/model/gradebook/GradebookComponent.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
  src/main/java/seedu/address/model/gradebook/UniqueComponentList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code

#66 Updated Developer Guide and User Guide
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/harriuscai.jpg
  docs/images/harriuscai.png
Labels: Changes in Documentation

#70 Updated my picture to an appropriate file format. Deleted some others.
  docs/AboutUs.adoc
  docs/images/damithc.jpg
  docs/images/lejolly.jpg
  docs/images/m-aslam-mj2.png
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
Labels: Changes in Documentation

#73 Updated relevant document with the class listing feature.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Changes in Documentation

#65 Implement Gradebook Find Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
  src/main/java/seedu/address/logic/commands/GradebookFindCommand.java
  src/main/java/seedu/address/logic/commands/GradebookListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GradebookAddCommandParser.java
  src/main/java/seedu/address/logic/parser/GradebookFindCommandParser.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/gradebook/GradebookComponent.java
  src/main/java/seedu/address/model/gradebook/MaxMarks.java
  src/main/java/seedu/address/model/gradebook/Name.java
  src/main/java/seedu/address/model/gradebook/UniqueComponentList.java
  src/main/java/seedu/address/model/gradebook/Weightage.java
Labels: Changes in Code, Changes in Documentation

#76 Changed file format of personal photo, and roles/responsibilities for…
  docs/AboutUs.adoc
  docs/images/jomcruz93.png
Labels: Changes in Documentation

#77 Modified storage, UI and 2 commands.
  classes.xml
  courseList.xml
  gradebook.xml
  modules.xml
  notes.xml
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/CourseListCommand.java
  src/main/java/seedu/address/logic/parser/CourseAddCommandParser.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/ui/ResultDisplay.java
Labels: Changes in Code, Changes in Shared Code, Changes in UX/UI Design

#79 Add support for listing modules in the system
  src/main/java/seedu/address/logic/commands/ModuleListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/NotesManager.java
  src/main/java/seedu/address/model/classroom/Classroom.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/main/java/seedu/address/model/gradebook/GradebookComponent.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
  src/main/java/seedu/address/model/note/Note.java
Labels: Changes in Code, Changes in Shared Code

#99 Course-related commands on new model/storage impl. Added tests. Updated docs.
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/CourseListCommand.java
  src/main/java/seedu/address/logic/parser/CourseAddCommandParser.java
  src/main/java/seedu/address/model/CourseManager.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/course/CourseManager.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedCourse.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedTag.java
  src/main/java/seedu/address/storage/serializable/XmlSerializableCourseList.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CourseAddCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Documentation, Changes in Shared Code, Changes in Testing Code

#96 Update interactions between classroom manager and storage controller and command
  src/main/java/seedu/address/logic/commands/ClassAddCommand.java
  src/main/java/seedu/address/logic/commands/ClassListCommand.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/classroom/ClassModule.java
  src/main/java/seedu/address/model/classroom/ClassName.java
  src/main/java/seedu/address/model/classroom/Classroom.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/main/java/seedu/address/model/classroom/Enrollment.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java
  src/main/java/seedu/address/storage/serializable/XmlSerializableClassroomList.java
  src/test/java/seedu/address/logic/commands/ClassAddCommandTest.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#102 Updated Gradebook Add Command
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/gradebook/Gradebook.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
Labels: Changes in Code

#103 Updated Gradebook List
  src/main/java/seedu/address/logic/commands/GradebookListCommand.java
  src/main/java/seedu/address/model/gradebook/Gradebook.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedGradebook.java
Labels: Changes in Code

#104 Updated gradebook find
  src/main/java/seedu/address/logic/commands/GradebookFindCommand.java
  src/main/java/seedu/address/model/gradebook/Gradebook.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
Labels: Approved with Minor Comments, Changes in Code

#112 Add support for deleting notes
  src/main/java/seedu/address/logic/commands/NoteAddCommand.java
  src/main/java/seedu/address/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/NoteListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NoteDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteListCommandParser.java
  src/main/java/seedu/address/model/note/NoteManager.java
Labels: Changes in Code

#114 Added course delete command, and HTML-based rendering.
  src/main/java/seedu/address/commons/events/ui/NewInfoMessageEvent.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/CourseDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CourseListCommand.java
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CourseAddCommandParser.java
  src/main/java/seedu/address/logic/parser/CourseDeleteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/course/CourseManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HtmlTableProcessor.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/seedu/address/logic/commands/CourseDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/StudentAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/StudentAddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/StudentAddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/StudentAddCommandSystemTest.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code, Changes in Testing Code, Changes in UX/UI Design

#109 Implemented Gradebook Delete Command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/GradebookDeleteCommand.java
  src/main/java/seedu/address/logic/parser/GradebookDeleteCommandParser.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
Labels: Changes in Code, Changes in Documentation

#116 Restored bootstrap. Updated app ver to 1.2, updated command help desc of a few commands.
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/CourseDeleteCommand.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/rendering/bootstrap.min.css
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code, Changes in UX/UI Design

#121 Added Test Case for Gradebook Add Command
  src/test/java/seedu/address/logic/commands/GradebookAddCommandTest.java
Labels: Changes in Testing Code

#117 Added support to delete classroom
  src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClassDeleteCommandParser.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/test/java/seedu/address/logic/commands/ClassDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/ClassDeleteCommandParserTest.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#122 Updated documentation for v1.2
  docs/DeveloperGuide.adoc
Labels: Changes in Documentation

#123 Updated UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Changes in Documentation

#124 Fix wrong javadoc comment used for `classdeletecommand` class
  src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
Labels: Changes in Code

#120 Enhanced class listing view
  src/main/java/seedu/address/logic/commands/ClassListCommand.java
  src/main/java/seedu/address/model/classroom/Classroom.java
Labels: Approved with Minor Comments, Changes in Code, priority.medium

#125 Updated command summary
  docs/UserGuide.adoc
Labels: Changes in Documentation

#126 developerguide.adoc update fix for wrongly placed section
  docs/DeveloperGuide.adoc
Labels: Changes in Documentation

#128 Fix typo in `ClassListCommand` class's javadoc
  src/main/java/seedu/address/logic/commands/ClassListCommand.java
Labels: Changes in Code

#127 Added proposed impl. details for user authentication system
  docs/DeveloperGuide.adoc
  docs/images/UserLoginActivityDiagram.png
Labels: Changes in Documentation

#130 Updated DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: Changes in Documentation

#132 Updated UI, and changed milestone for a feature.
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: Changes in Documentation

#131 Added implementation details on a future module bidding feature in DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/moduleBiddingActivityDiagram.png
Labels: Changes in Documentation

#140 Updated Gradebook Find Command
  src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
  src/main/java/seedu/address/logic/commands/GradebookFindCommand.java
  src/main/java/seedu/address/logic/commands/GradebookListCommand.java
  src/main/java/seedu/address/model/gradebook/Gradebook.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
Labels: Changes in Code

#142 Modified Course Manager to adopt a singleton approach.
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/CourseDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CourseListCommand.java
  src/main/java/seedu/address/model/course/CourseManager.java
Labels: Changes in Code

#143 Implemented validation on user input when using module-related commands
  src/main/java/seedu/address/logic/commands/ModuleEditCommand.java
  src/main/java/seedu/address/logic/commands/ModuleListCommand.java
  src/main/java/seedu/address/logic/parser/ModuleAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ModuleEditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleManager.java
  src/main/java/seedu/address/model/module/ModuleName.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedModule.java
  src/test/java/seedu/address/model/module/ModuleCodeTest.java
  src/test/java/seedu/address/model/module/ModuleNameTest.java
Labels: Changes in Code, Changes in Testing Code

#144 Code enhancements - Validation for class-related commands
  src/main/java/seedu/address/logic/commands/ClassAddCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ClassListCommand.java
  src/main/java/seedu/address/logic/parser/ClassAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassroomParserUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/classroom/ClassModule.java
  src/main/java/seedu/address/model/classroom/ClassName.java
  src/main/java/seedu/address/model/classroom/Classroom.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/main/java/seedu/address/model/classroom/Enrollment.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java
  src/test/java/seedu/address/model/classroom/ClassModuleTest.java
  src/test/java/seedu/address/model/classroom/ClassNameTest.java
  src/test/java/seedu/address/model/classroom/ClassroomTest.java
  src/test/java/seedu/address/model/classroom/EnrollmentTest.java
  src/test/java/seedu/address/testutil/ClassroomBuilder.java
  src/test/java/seedu/address/testutil/TypicalClassrooms.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#147 Improved the command parser regex to allow multi-letter prefixes
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: Changes in Shared Code

#148 Update implementation to make use of ModuleCode
  src/main/java/seedu/address/logic/commands/ClassAddCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
  src/main/java/seedu/address/logic/parser/ClassAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassroomParserUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/classroom/ClassModule.java
  src/main/java/seedu/address/model/classroom/Classroom.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java
  src/test/java/seedu/address/logic/commands/ClassAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CourseAddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/classroom/ClassModuleTest.java
  src/test/java/seedu/address/model/classroom/ClassroomTest.java
  src/test/java/seedu/address/testutil/ClassroomBuilder.java
  src/test/java/seedu/address/testutil/TypicalClassrooms.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#157 Implemented storage for user auth. system
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/model/user/UserManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedUser.java
  src/main/java/seedu/address/storage/serializable/XmlSerializableUserList.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code

#159 Adjustment to codes for Note Management feature
  src/main/java/seedu/address/logic/commands/NoteAddCommand.java
  src/main/java/seedu/address/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/NoteEditCommand.java
  src/main/java/seedu/address/logic/commands/NoteListCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteEditCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteListCommandParser.java
  src/main/java/seedu/address/model/note/NoteManager.java
  src/main/java/seedu/address/ui/NoteTextEditWindow.java
  src/test/java/seedu/address/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
  src/test/java/seedu/address/model/note/NoteManagerTest.java
Labels: Changes in Code, Changes in Testing Code

#161 Added login capability, refactored student commands.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/DebugCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/StudentEditCommand.java
  src/main/java/seedu/address/logic/commands/StudentFindCommand.java
  src/main/java/seedu/address/logic/commands/StudentListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/ui/HtmlTableProcessor.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code, Changes in Testing Code

#167 Added implementation for Classroom editing
  src/main/java/seedu/address/logic/commands/ClassEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClassEditCommandParser.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
Labels: Changes in Code, Changes in Shared Code

#168 Updated Gradebook Delete Command
  src/main/java/seedu/address/logic/commands/GradebookDeleteCommand.java
  src/main/java/seedu/address/logic/parser/GradebookDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/GradebookEditCommandParser.java
  src/main/java/seedu/address/model/gradebook/Gradebook.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedGradebook.java
  src/test/java/seedu/address/logic/commands/GradebookDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/GradebookDeleteCommandParserTest.java
Labels: Changes in Code, Changes in Testing Code

#170 Added implementation for assigning student to classroom
  src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClassAddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/classroom/Classroom.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code

#183 Added HTML for gradebook list and find
  src/main/java/seedu/address/logic/commands/GradebookFindCommand.java
  src/main/java/seedu/address/logic/commands/GradebookListCommand.java
  src/main/java/seedu/address/model/gradebook/Gradebook.java
  src/test/java/seedu/address/logic/commands/GradebookFindCommandTest.java
Labels: Changes in Code

#182 Note list is displayed in WebView panel
  src/main/java/seedu/address/logic/commands/NoteAddCommand.java
  src/main/java/seedu/address/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/NoteEditCommand.java
  src/main/java/seedu/address/logic/commands/NoteListCommand.java
  src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteEditCommandParser.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/note/NoteManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedNote.java
  src/main/java/seedu/address/ui/HtmlCardProcessor.java
  src/main/java/seedu/address/ui/NoteEntryPrompt.java
  src/main/resources/view/NoteEntryPromptWindow.fxml
  src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
  src/test/java/seedu/address/model/note/NoteManagerTest.java
  src/test/java/seedu/address/testutil/NoteBuilder.java
Labels: Changes in Code, type.enhancement

#175 Updated Gradebook Edit Command
  src/main/java/seedu/address/logic/commands/GradebookEditCommand.java
  src/main/java/seedu/address/logic/parser/GradebookEditCommandParser.java
  src/test/java/seedu/address/logic/commands/GradebookDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookEditCommandTest.java
  src/test/java/seedu/address/logic/parser/GradebookEditCommandParserTest.java
Labels: Changes in Code, Changes in Testing Code

#171 Implemented Student Manager APIs to search by matric no/email.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/student/StudentManager.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code

#184 Added new feature to export notes to CSV
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/NoteEditCommand.java
  src/main/java/seedu/address/logic/commands/NoteExportCommand.java
  src/main/java/seedu/address/logic/commands/NoteListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteExportCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteListCommandParser.java
  src/main/java/seedu/address/model/note/NoteManager.java
  src/main/java/seedu/address/storage/adapter/CsvAdaptedNote.java
  src/main/java/seedu/address/ui/HtmlCardProcessor.java
  src/main/java/seedu/address/ui/NoteEntryPrompt.java
  src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
  src/test/java/seedu/address/model/note/NoteManagerTest.java
  src/test/java/seedu/address/testutil/NoteBuilder.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code, Changes in Testing Code, Changes in UX/UI Design

#185 Improvements to Course-related code and entities
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/CourseDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CourseListCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/logic/commands/StudentEditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassAddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassDeleteStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/CourseAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/course/CourseCode.java
  src/main/java/seedu/address/model/course/CourseManager.java
  src/main/java/seedu/address/model/course/CourseName.java
  src/main/java/seedu/address/model/course/FacultyName.java
  src/main/java/seedu/address/model/person/MatricNo.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedCourse.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CourseAddCommandTest.java
  src/test/java/seedu/address/logic/commands/StudentAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/StudentAddCommandTest.java
  src/test/java/seedu/address/testutil/CourseBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code, Changes in Testing Code

#188 Added basic implementation to enrol a student in a module
  config.json
  src/main/java/seedu/address/logic/commands/ModuleEnrolCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ModuleEnrolCommandParser.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedStudentModule.java
  src/main/java/seedu/address/storage/serializable/XmlSerializableStudentModuleList.java
Labels: Changes in Code, Changes in Shared Code

#190 Fixed bug with Student Manager APIs, added 'welcome screen' to WebView.
  config.json
  src/main/java/seedu/address/model/student/StudentManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/HtmlTableProcessor.java
Labels: Changes in Code, Changes in Shared Code

#191 Bug fixes in ModuleManager and StudentManager
  src/main/java/seedu/address/logic/commands/ModuleEnrolCommand.java
  src/main/java/seedu/address/logic/commands/ModuleListCommand.java
  src/main/java/seedu/address/model/module/ModuleManager.java
  src/main/java/seedu/address/model/student/StudentManager.java
Labels: Changes in Code

#193 Enabled support for enrolling multiple students into a module in one shot
  src/main/java/seedu/address/logic/commands/ModuleEnrolCommand.java
  src/main/java/seedu/address/logic/parser/ModuleEnrolCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/ModuleManager.java
  src/test/java/seedu/address/model/module/ModuleNameTest.java
Labels: Changes in Code

#202 Added implementation for classroom attendance
  src/main/java/seedu/address/logic/commands/ClassAddCommand.java
  src/main/java/seedu/address/logic/commands/ClassAddStudentAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/ClassEditCommand.java
  src/main/java/seedu/address/logic/commands/ClassListStudentAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClassListStudentAttendanceCommandParser.java
  src/main/java/seedu/address/model/classroom/Attendance.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroomAttendance.java
Labels: Changes in Code

#203 Implemented Grade feature
  src/main/java/seedu/address/logic/commands/GradeAddCommand.java
  src/main/java/seedu/address/logic/commands/GradeGraphCommand.java
  src/main/java/seedu/address/logic/commands/GradeListCommand.java
  src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
  src/main/java/seedu/address/logic/commands/GradebookDeleteCommand.java
  src/main/java/seedu/address/logic/commands/GradebookEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GradeAddCommandParser.java
  src/main/java/seedu/address/logic/parser/GradeGraphCommandParser.java
  src/main/java/seedu/address/logic/parser/GradebookAddCommandParser.java
  src/main/java/seedu/address/logic/parser/GradebookEditCommandParser.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
  src/main/java/seedu/address/model/grades/Grades.java
  src/main/java/seedu/address/model/grades/GradesManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedGradebook.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedGrades.java
  src/main/java/seedu/address/storage/serializable/XmlSerializableGradeList.java
  src/main/java/seedu/address/ui/GradeGraphDisplay.java
  src/test/java/seedu/address/logic/commands/GradeAddCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookEditCommandTest.java
  src/test/java/seedu/address/logic/parser/GradeAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookFindCommandParserTest.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code, Changes in Testing Code

#201 Added data validation to note attributes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/NoteAddCommand.java
  src/main/java/seedu/address/logic/commands/NoteEditCommand.java
  src/main/java/seedu/address/logic/commands/NoteExportCommand.java
  src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteEditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/note/NoteDate.java
  src/main/java/seedu/address/model/note/NoteLocation.java
  src/main/java/seedu/address/model/note/NoteManager.java
  src/main/java/seedu/address/model/note/NoteText.java
  src/main/java/seedu/address/model/note/NoteTime.java
  src/main/java/seedu/address/model/note/NoteTitle.java
  src/main/java/seedu/address/storage/adapter/CsvAdaptedNote.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedNote.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/HtmlCardProcessor.java
  src/main/java/seedu/address/ui/NoteEntryPrompt.java
  src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteExportCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
  src/test/java/seedu/address/model/note/NoteManagerTest.java
  src/test/java/seedu/address/testutil/NoteBuilder.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code, Changes in UX/UI Design, type.enhancement

#213 Improved validation for course and students. Added testMode for Storage Controller.
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/DebugCommand.java
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/logic/commands/StudentListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/course/CourseCode.java
  src/main/java/seedu/address/model/course/CourseName.java
  src/main/java/seedu/address/model/student/StudentManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CourseAddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/StudentAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/StudentAddCommandTest.java
  src/test/java/seedu/address/logic/parser/StudentAddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#216 Added support to delete multiple notes by index
  src/main/java/seedu/address/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NoteDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/storage/adapter/CsvAdaptedNote.java
  src/main/java/seedu/address/ui/NoteEntryPrompt.java
  src/test/java/seedu/address/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteDeleteCommandParserTest.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code, Changes in Testing Code, type.enhancement

#217 Users can now view a module's details
  src/main/java/seedu/address/logic/commands/ModuleViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ModuleViewCommandParser.java
Labels: Changes in Code, Changes in Shared Code

#218 Added validations to user input for class-related commands
  src/main/java/seedu/address/logic/commands/ClassAddCommand.java
  src/main/java/seedu/address/logic/commands/ClassAddStudentAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteStudentAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/ClassEditCommand.java
  src/main/java/seedu/address/logic/commands/ClassListCommand.java
  src/main/java/seedu/address/logic/commands/ClassListStudentAttendanceCommand.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroomAttendance.java
  src/test/java/seedu/address/logic/commands/ClassAddCommandTest.java
Labels: Changes in Code

#222 Course list refreshes when course is deleted. Added CourseListStudentCommand.
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/CourseDeleteCommand.java
  src/main/java/seedu/address/logic/commands/CourseListStudentsCommand.java
  src/main/java/seedu/address/logic/commands/StudentListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/course/CourseCode.java
  src/main/java/seedu/address/model/course/CourseManager.java
  src/main/java/seedu/address/model/student/StudentManager.java
  src/main/java/seedu/address/ui/HtmlTableProcessor.java
Labels: Approved with Minor Comments, Changes in Code, Changes in Shared Code

#224 Updated Grade and Gradebook
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/GradeAddCommand.java
  src/main/java/seedu/address/logic/commands/GradeGraphCommand.java
  src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
  src/main/java/seedu/address/logic/commands/GradebookDeleteCommand.java
  src/main/java/seedu/address/logic/commands/GradebookEditCommand.java
  src/main/java/seedu/address/logic/commands/GradebookFindCommand.java
  src/main/java/seedu/address/logic/commands/GradebookListCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GradeAddCommandParser.java
  src/main/java/seedu/address/logic/parser/GradeGraphCommandParser.java
  src/main/java/seedu/address/logic/parser/GradebookAddCommandParser.java
  src/main/java/seedu/address/logic/parser/GradebookDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/GradebookEditCommandParser.java
  src/main/java/seedu/address/logic/parser/GradebookFindCommandParser.java
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
  src/main/java/seedu/address/model/grades/GradesManager.java
  src/test/java/seedu/address/logic/commands/GradeAddCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookAddCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookEditCommandTest.java
  src/test/java/seedu/address/logic/parser/GradeAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookFindCommandParserTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code, Changes in Testing Code

#225 Fixed formatting, and changed display of main window.
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/StudentAddCommandSystemTest.java
Labels: Changes in Code, Changes in Shared Code, Changes in UX/UI Design

#226 Doc update
  docs/UserGuide.adoc
Labels: Changes in Documentation

#227 Add character limit to TextArea on Note add/edit window prompt
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/NoteAddCommand.java
  src/main/java/seedu/address/logic/commands/NoteEditCommand.java
  src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteEditCommandParser.java
  src/main/java/seedu/address/model/note/NoteLocation.java
  src/main/java/seedu/address/model/note/NoteTitle.java
  src/main/java/seedu/address/ui/NoteEntryPrompt.java
  src/main/java/seedu/address/ui/NoteTextEditWindow.java
  src/main/resources/view/NoteEntryPromptWindow.fxml
Labels: Changes in Code, Changes in UX/UI Design, type.enhancement

#228 Users can now search for modules
  src/main/java/seedu/address/logic/commands/ModuleFindCommand.java
  src/main/java/seedu/address/logic/commands/ModuleListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ModuleFindCommandParser.java
  src/main/java/seedu/address/model/module/ModuleManager.java
Labels: Changes in Code, Changes in Shared Code

#229 Update of UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Changes in Documentation

#230 Updated ModuleManagement section in the UserGuide
  docs/UserGuide.adoc
Labels: Changes in Documentation

#233 * Handles removal of module and removal of student
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
Labels: Changes in Code

#234 Updated UG and minor additions to test codes.
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/ui/NoteEntryPrompt.java
  src/test/java/seedu/address/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteExportCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteFindCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Testing Code

#235 Enhanced module delete
  src/main/java/seedu/address/logic/commands/ModuleDeleteCommand.java
  src/main/java/seedu/address/logic/parser/ModuleDeleteCommandParser.java
Labels: Changes in Code

#236 Updated UG command summary
  docs/UserGuide.adoc
Labels: Changes in Documentation

#238 Updated UG and enhanced module delete
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/module/ModuleManager.java
Labels: Changes in Code, Changes in Documentation

#240 Changes to UG and DG. Student commands to auto-refresh. Changes in storage controller.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/CourseListStudentsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/logic/commands/StudentEditCommand.java
  src/main/java/seedu/address/logic/commands/StudentFindCommand.java
  src/main/java/seedu/address/logic/commands/StudentListCommand.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/student/StudentManager.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code

#242 Added the view module feature to the DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Changes in Documentation

#243 Enhancement to automatically display updated class attendance
  src/main/java/seedu/address/logic/commands/ClassAddStudentAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteStudentAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ClassListStudentAttendanceCommand.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
Labels: Approved with Minor Comments, Changes in Code

#245 Fixed a minor mistake in the command summary of UG
  docs/UserGuide.adoc
Labels: Changes in Documentation

#246 Fixed bugs.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/StorageController.java
Labels: Changes in Shared Code
