Repository CS2113-AY1819S1-T16-1/main, pull requests merged in 2018-09, with the labels that each got.

#24 [Update] Ported my part of user stories
  docs/DeveloperGuide.adoc
Labels: change.documentation

#27 Ported User Stories and Use Cases to developer guide
  docs/DeveloperGuide.adoc
Labels: change.documentation

#29 updated dev guide and user guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: change.documentation

#28 Updated DeveloperGuide.adoc file
  docs/DeveloperGuide.adoc
Labels: Changes in Documentation

#31 Update UserGuide.adoc
  docs/UserGuide.adoc
Labels: Changes in Documentation

#32 Added Class Management to user guide document
  docs/UserGuide.adoc
Labels: Changes in Documentation

#37 Updated user doc with commands summary for Class Management
  docs/UserGuide.adoc
Labels: Changes in Documentation

#38 Updated AboutUs, UserGuide and DeveloperGuide
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Changes in Documentation

#39 Shifted Notes Management below Gradebook Management
  docs/UserGuide.adoc
Labels: Changes in Documentation

#46 Updated User Guide and Developer Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Changes in Documentation

#35 Updated user guide, morphed a bit of GUI, created basic student classes, modified tests
  config/checkstyle/suppressions.xml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/StudentDatabase.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/student/Student2.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/GuiRobot.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code

#47 Changed use cases and command format for grade management
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Changes in Documentation

#48 Updated format for all use cases
  docs/DeveloperGuide.adoc
Labels: Changes in Documentation
