Repository CS2113-AY1819S1-T16-1/main, pull requests merged in 2018-11, with the labels that each got.

#254 Changed file path separator to "/" instead of "\" for note export
  src/main/java/seedu/address/commons/util/CsvUtil.java
Labels: Changes in Code

#257 Fixed a bug in note edit command
  src/main/java/seedu/address/logic/commands/NoteEditCommand.java
Labels: Changes in Code

#284 Corrected error message when entering invalid parameters for note add command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
Labels: Changes in Code

#286 Update UG to fix error in documentation
  docs/UserGuide.adoc
Labels: Changes in Documentation

#290 Introduced the draft documentation of the PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/zhicaizack.adoc
Labels: Changes in Documentation

#291 Rectified issues found in PE1
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code, Changes in Testing Code

#292 Project Portfolio Page
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/tristyxxnana.adoc
Labels: Changes in Documentation

#293 Added my PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jomcruz93.adoc
Labels: Changes in Documentation

#295 Added my first draft of the PPP.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/m-aslam-mj2.adoc
Labels: Changes in Documentation

#297 Enhancement to Note Delete Command
  src/main/java/seedu/address/logic/commands/NoteDeleteCommand.java
  src/main/java/seedu/address/logic/commands/NoteFindCommand.java
  src/main/java/seedu/address/logic/parser/NoteDeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/NoteFindCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
Labels: Changes in Code, Changes in Testing Code

#298 Validates whether a student is enrolled into a module before assigning the student to classroom
  src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteStudentCommand.java
Labels: Changes in Code

#299 Removed validation for duplicate indexes for faster execution
  src/main/java/seedu/address/logic/parser/NoteDeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/NoteDeleteCommandParserTest.java
Labels: Changes in Code, Changes in Testing Code

#300 Fix some formatting issues in the User Guide
  docs/UserGuide.adoc
Labels: Changes in Documentation

#302 Update the UI compoenent of developer guide
  docs/DeveloperGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/UiClassDiagram.png
Labels: Changes in Documentation

#304 Added tests, added splash screen, added pre-typed commands.
  docs/team/m-aslam-mj2.adoc
  inputs.txt
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/ExpeditedInputs.java
  src/main/java/seedu/address/logic/commands/CourseListCommand.java
  src/main/java/seedu/address/logic/commands/DebugCommand.java
  src/main/java/seedu/address/model/StorageController.java
  src/main/java/seedu/address/model/course/CourseManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HtmlTableProcessor.java
  src/main/resources/view/default.html
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CourseAddCommandTest.java
  src/test/java/seedu/address/logic/commands/CourseDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/CourseListCommandTest.java
  src/test/java/seedu/address/logic/parser/StudentAddCommandParserTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code, Changes in Testing Code

#312 Added test methods
  docs/UserGuide.adoc
  docs/team/tristyxxnana.adoc
  src/main/java/seedu/address/logic/commands/GradeAddCommand.java
  src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
  src/main/java/seedu/address/model/grades/GradesManager.java
  src/test/java/seedu/address/logic/commands/GradeAddCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookAddCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookFindCommandTest.java
  src/test/java/seedu/address/logic/parser/GradeAddCommandParserTest.java
  src/test/java/seedu/address/testutil/GradeBuilder.java
  src/test/java/seedu/address/testutil/GradebookBuilder.java
Labels: Changes in Code, Changes in Documentation, Changes in Testing Code

#311 Fixed checkstyle violations in tests
  src/test/java/seedu/address/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteFindCommandTest.java
Labels: Changes in Testing Code

#316 Updated Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/GradebookDeleteSDForLogic.png
  docs/images/TrajectoryLogicClassDiagram.png
  docs/team/tristyxxnana.adoc
  src/main/java/seedu/address/model/gradebook/GradebookManager.java
  src/main/java/seedu/address/model/grades/Grades.java
Labels: Changes in Code, Changes in Documentation

#315 Added new class diagram files for Model component
  docs/diagrams/ClassroomModelComponentClassDiagram.pptx
  docs/diagrams/CompleteModelComponentClassDiagram.pptx
  docs/diagrams/CourseModelComponentClassDiagram.pptx
  docs/diagrams/GradebookModelComponentClassDiagram.pptx
  docs/diagrams/GradesModelComponentClassDiagram.pptx
  docs/diagrams/ModuleModelComponentClassDiagram.pptx
  docs/diagrams/NoteModelComponentClassDiagram.pptx
  docs/diagrams/StudentModelComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
Labels: Changes in Documentation

#320 Updated Model component description in DG
  docs/DeveloperGuide.adoc
  docs/images/ModelClassDiagram.png
Labels: Changes in Documentation

#319 Set MODULE_CODE as optional parameter when creating notes..
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/NoteAddCommand.java
  src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
  src/main/java/seedu/address/model/note/NoteManager.java
  src/main/java/seedu/address/model/note/NoteText.java
  src/main/java/seedu/address/storage/adapter/CsvAdaptedNote.java
  src/main/java/seedu/address/storage/adapter/XmlAdaptedNote.java
  src/main/java/seedu/address/ui/NoteEntryPrompt.java
  src/test/java/seedu/address/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteExportCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteFindCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
  src/test/java/seedu/address/model/note/NoteManagerTest.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code, Changes in UX/UI Design

#322 Added Instructions for Manual Testing for Notes feature in DG
  docs/DeveloperGuide.adoc
Labels: Changes in Documentation

#321 Replaced activity diagram in implementation section
  docs/DeveloperGuide.adoc
  docs/images/GradeGraphActivityDiagram.png
Labels: Changes in Documentation

#318 Add testcase for classroom features
  src/main/java/seedu/address/logic/commands/ClassAddCommand.java
  src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ClassDeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/ClassEditCommand.java
  src/main/java/seedu/address/logic/parser/ClassAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassAddStudentAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassAddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassDeleteStudentAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassDeleteStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassEditCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassListStudentAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/ClassroomParserUtil.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
  src/test/java/seedu/address/logic/commands/ClassAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClassAddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/ClassDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ClassDeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/ClassEditCommandTest.java
  src/test/java/seedu/address/logic/commands/ClassListCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ClassAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClassDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClassEditCommandParserTest.java
  src/test/java/seedu/address/model/classroom/EnrollmentTest.java
Labels: Changes in Code, Changes in Testing Code

#323 Removed redundant class in NoteManager
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/note/NoteManager.java
  src/test/java/seedu/address/logic/commands/NoteDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteExportCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteFindCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
  src/test/java/seedu/address/model/note/NoteManagerTest.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#326 Changed directory of exported CSV files
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/NoteExportCommand.java
  src/main/java/seedu/address/model/note/NoteManager.java
  src/test/java/seedu/address/logic/commands/NoteExportCommandTest.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#313 Auto-complete commands with TAB
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: Changes in Shared Code, Changes in Testing Code, UNDER REVIEW

#327 Added more test cases
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/note/NoteLocation.java
  src/main/java/seedu/address/model/note/NoteText.java
  src/main/java/seedu/address/model/note/NoteTime.java
  src/main/java/seedu/address/model/note/NoteTitle.java
  src/test/java/seedu/address/commons/util/CsvUtilTest.java
  src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/NoteBuilder.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#328 Completed the write-up on the Architecture design section of the DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/images/Architecture.png
  docs/images/SDforMVCPattern.png
Labels: Changes in Documentation

#330 Added lock/unlock capability. Expedited commands now require modifier key.
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DebugCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/model/user/UserManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HtmlTableProcessor.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: Changes in Code, Changes in Shared Code, Changes in Testing Code

#332 Updated DG. Added 'course edit' command and fixed a bug with 'student edit'.
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/CourseEditCommand.java
  src/main/java/seedu/address/logic/commands/StudentEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CourseEditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/course/CourseManager.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code, Changes in Testing Code

#333 Updated UG, DG, and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/NoteExportSequenceDiagram.pptx
  docs/images/NoteExportSequenceDiagram.png
  docs/team/jomcruz93.adoc
Labels: Changes in Documentation

#334 Add UI support for module list and find
  src/main/java/seedu/address/logic/commands/ModuleAddCommand.java
  src/main/java/seedu/address/logic/commands/ModuleFindCommand.java
  src/main/java/seedu/address/logic/commands/ModuleListCommand.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleManager.java
Labels: Changes in Code

#335 Added validation if module exists when adding notes to module.
  src/main/java/seedu/address/logic/commands/NoteAddCommand.java
  src/main/java/seedu/address/logic/commands/NoteEditCommand.java
  src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteEditCommandParser.java
  src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
Labels: Changes in Code, Changes in Testing Code

#336 Added a few tests.
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CourseAddCommand.java
  src/main/java/seedu/address/logic/commands/CourseDeleteCommand.java
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/course/FacultyName.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/CourseAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CourseDeleteCommandParserTest.java
  src/test/java/seedu/address/model/course/CourseCodeTest.java
  src/test/java/seedu/address/model/course/CourseNameTest.java
  src/test/java/seedu/address/model/course/FacultyNameTest.java
  src/test/java/seedu/address/testutil/CourseBuilder.java
Labels: Changes in Code, Changes in Testing Code

#337 Docupdate for Manual Test, Fixes in UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/zhicaizack.adoc
  src/main/java/seedu/address/model/classroom/ClassName.java
Labels: Changes in Code, Changes in Documentation

#338 Add UI support for module view, enrol, add, delete, and edit
  src/main/java/seedu/address/logic/commands/ModuleAddCommand.java
  src/main/java/seedu/address/logic/commands/ModuleDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ModuleEditCommand.java
  src/main/java/seedu/address/logic/commands/ModuleEnrolCommand.java
  src/main/java/seedu/address/logic/commands/ModuleViewCommand.java
  src/main/java/seedu/address/model/module/ModuleManager.java
  src/main/java/seedu/address/ui/HtmlProcessor.java
  src/main/java/seedu/address/ui/HtmlTableProcessor.java
Labels: Changes in Code

#339 Changed display of class related info to banner type
  src/main/java/seedu/address/model/classroom/ClassroomManager.java
Labels: Changes in Code

#341 Updated UG and DG.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
  docs/team/m-aslam-mj2.adoc
Labels: Changes in Documentation

#342 Fix some checkstyle errors
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleEditCommandParserTest.java
  src/test/java/seedu/address/model/module/ModuleCodeTest.java
  src/test/java/seedu/address/model/module/ModuleNameTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: Changes in Testing Code

#343 Added uml diagram into DG
  docs/DeveloperGuide.adoc
  docs/diagrams/ClassAddSequenceDiagram.pptx
  docs/images/ClassAddSequenceDiagram.png
Labels: Changes in Documentation

#344 Test Files Added for Grade and Gradebook
  src/main/java/seedu/address/logic/commands/GradeListCommand.java
  src/main/java/seedu/address/logic/commands/GradebookDeleteCommand.java
  src/main/java/seedu/address/logic/commands/GradebookEditCommand.java
  src/main/java/seedu/address/logic/commands/GradebookFindCommand.java
  src/main/java/seedu/address/logic/commands/GradebookListCommand.java
  src/test/java/seedu/address/logic/commands/GradeAddCommandTest.java
  src/test/java/seedu/address/logic/commands/GradeListCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookAddCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookEditCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookFindCommandTest.java
  src/test/java/seedu/address/logic/commands/GradebookListCommandTest.java
  src/test/java/seedu/address/logic/parser/GradeAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradebookFindCommandParserTest.java
  src/test/java/seedu/address/testutil/GradeBuilder.java
  src/test/java/seedu/address/testutil/GradebookBuilder.java
  testStorage/classAttendance.xml
  testStorage/classes.xml
  testStorage/courseList.xml
  testStorage/gradebook.xml
  testStorage/grades.xml
  testStorage/modules.xml
  testStorage/notes.xml
  testStorage/studentModule.xml
  testStorage/users.xml
Labels: Changes in Code, Changes in Documentation

#345 Updated the rendering of HTML cards for notes
  src/main/java/seedu/address/model/note/NoteManager.java
  src/main/java/seedu/address/ui/HtmlCardProcessor.java
Labels: Changes in Code, Changes in UX/UI Design

#346 Fixed CS errors, added some tests, updated PPP.
  .gitignore
  config/checkstyle/suppressions.xml
  docs/diagrams/LockUnlockSequenceDiagram.pptx
  docs/images/LockUnlockSequenceDiagram.png
  docs/team/m-aslam-mj2.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/CourseEditCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/StorageController.java
  src/test/java/seedu/address/commons/util/CsvUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
  src/test/java/seedu/address/logic/commands/StudentAddCommandTest.java
  src/test/java/seedu/address/logic/parser/CourseEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditCourseDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  testStorage/classAttendance.xml
  testStorage/classes.xml
  testStorage/courseList.xml
  testStorage/gradebook.xml
  testStorage/grades.xml
  testStorage/modules.xml
  testStorage/notes.xml
  testStorage/studentModule.xml
  testStorage/users.xml
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code, Changes in Testing Code

#347 Populate sample data
  src/main/java/seedu/address/logic/commands/DebugCommand.java
Labels: Changes in Code

#348 Fix visual bug on DG and shorten PPP
  docs/DeveloperGuide.adoc
  docs/images/sequencediagramclassadd.png
  docs/team/zhicaizack.adoc
Labels: Changes in Documentation

#349 Updated student list view. Updated UG and DG. Updated build.gradle.
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/student/StudentManager.java
  src/test/java/seedu/address/logic/commands/StudentAddCommandIntegrationTest.java
Labels: Changes in Code, Changes in Documentation, Changes in Shared Code

#351 Updated DG. Updated PPP to reduce no. of pages
  docs/DeveloperGuide.adoc
  docs/team/jomcruz93.adoc
Labels: Changes in Documentation

#352 Update UG, DG, PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/zhicaizack.adoc
Labels: Changes in Documentation

#350 Adoc update
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/tristyxxnana.adoc
Labels: Changes in Documentation

#353 Populated Gradebook Grade Data
  src/main/java/seedu/address/logic/commands/DebugCommand.java
Labels: Changes in Shared Code

#354 Completed PPP and added manual testing instructions
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/harriuscai.adoc
Labels: Changes in Documentation

#357 Added notes data in debug command
  src/main/java/seedu/address/logic/commands/DebugCommand.java
Labels: Changes in Code, Changes in Shared Code

#356 Modified docs.
  build.gradle
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/trjlogo.png
  docs/team/m-aslam-mj2.adoc
  docs/templates/_header.html.slim
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/star_32.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/default.html
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/CourseListCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
Labels: Changes in Documentation
